
export default {
    NEW_USER: 'NEW_USER',
    EDIT_USER: 'EDIT_USER',
    YES_LOADING: 'YES_LOADING',
    FINISH_LOADING: 'FINISH_LOADING',
    SET_USERS: 'SET_USERS',
    POST_SUCCESS: 'POST_SUCCESS',
    POST_ERROR: 'POST_ERROR',
    FALSE_POST: 'FALSE_POST' 
  }